# Docker Registry Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - docker-registry
            topologyKey: kubernetes.io/hostname
      containers:
      - name: docker-registry
        image: docker.io/registry
        ports:
        - containerPort: 5000
        - containerPort: 443
        env:
        - name: REGISTRY_HTTP_HOST
          value: registry.redcloud.land
        - name: REGISTRY_HTTP_SECRET
          value: "ZQ3PExhnt2SwhK" # ransome stuff
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/registry.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/registry.key
        # Adding AUTH TBD
        # - name: REGISTRY_AUTH=token
        # - name: REGISTRY_AUTH_TOKEN_REALM=https://something.redcloud.land/auth
        # - name: REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
        # - name: REGISTRY_AUTH_TOKEN_ISSUER="RedCloud Auth Server"
        # - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/domain.crt
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
        - mountPath: "/certs"
          name: registry-tls
          readOnly: true
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data-pvc
      - name: registry-tls
        secret:
          secretName: registry-tls
          items:
            - key: registry.crt
              path: registry.crt
            - key: registry.key
              path: registry.key
